### ISSUE TITLE
Aurelia Webpack

### ISSUE THREAD

**Issue by domenkogler** [unitejs/cli#4]
Hello,

congrats on excellent project.

Aurelia has [new webpack @3.0.0-rc.1](https://github.com/aurelia/webpack-plugin/releases/tag/3.0.0-rc.1) plugin, please include it in unitejs.

**Comment by obany** [comment]
It's definitely something planned, I had a lot of problems trying to integrate the previous plugin. Hopefully this one will integrate more smoothly!

**Comment by istrau2** [comment]
I have an aurelia webpack project currently in production. I would like to try and produce an electron version of the app. 

The app is modeled after https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack although the webpack workflow is more complex.

Any ideas on how I can use this project to produce an electron version of the app?

**Comment by obany** [comment]
We still don't support aurelia webpack as a combination so this isn't a possibility at the moment.
