### ISSUE TITLE
issue while creating Vue app via cli

### ISSUE THREAD

**Issue by ka6tk** [unitejs/cli#6]
`$ unite configure --packageName=abc --profile=VueJavaScript --unitTestRunner="None" --e2eTestRunner="None" --documenter="None" --title="sample app"
`

For the above command i am getting following response.
`UniteJS CLI
Engine v1.7.11

command: configure
profile: VueJavaScript
packageName: abc
sourceLanguage: JavaScript
moduleType: CommonJs
bundler: Webpack
ERROR: unitTestFramework is not valid if unitTestRunner is None`

not generating the application

**Comment by obany** [comment]
There is an issue with setting the unitTestRunner to none when the profile has it set, the only way round this at the moment is to configure all of the options manually and not use the profile.

**Comment by obany** [comment]
Fixed in 1.7.12
